### ISSUE TITLE
🔧

### ISSUE THREAD

**Issue by PocketKiller** [Lucario2/Trouble-with-plugins#1]

**Comment by Lucario2** [comment]
Excuse me. I am here to learn how to code. Not for some stupid ___ person
who I banned

**Comment by PocketKiller** [comment]
the repo is empty.

**Comment by PocketKiller** [comment]
naturally you are so **stupid

**Comment by Lucario2** [comment]
Okay.

**Comment by Lucario2** [comment]
I will unban you. If you want. I am sorry. I don't even know what happened xD

**Comment by PocketKiller** [comment]
do you know i was just playing with you here? XD

**Comment by Lucario2** [comment]
No?

**Comment by PocketKiller** [comment]
not "No" it was long ago, so idc anymore

**Comment by PocketKiller** [comment]
and yeah, on your server comments, most of them contain "this server is bad, owner bans everyone"

**Comment by Lucario2** [comment]
Oh...

**Comment by Lucario2** [comment]
Do u code? I want you on my dev team.

**Comment by PocketKiller** [comment]
yes i code too much

**Comment by Lucario2** [comment]
It's hater comments

**Comment by PocketKiller** [comment]
i work on Genisys, ImagicalMine, and make minigames.

**Comment by Lucario2** [comment]
Kewl

**Comment by PocketKiller** [comment]
> It's hater comments

thats true

**Comment by Lucario2** [comment]
What's your kik?

**Comment by PocketKiller** [comment]
Taha_The_Hacker

**Comment by Lucario2** [comment]
oh

**Comment by PocketKiller** [comment]
now, what do you want me to do with that?

**Comment by Lucario2** [comment]
hllo

**Comment by PocketKiller** [comment]
hello

**Comment by Lucario2** [comment]
Okay

**Comment by Lucario2** [comment]
http://collabedit.com/w99mt

**Comment by PocketKiller** [comment]
i meant

**Comment by PocketKiller** [comment]
what do you want me to edit on TDroidd's plugin?

**Comment by Lucario2** [comment]
Ho

**Comment by PocketKiller** [comment]
?

**Comment by Lucario2** [comment]
yes

**Comment by Lucario2** [comment]
I just got ddosed

**Comment by PocketKiller** [comment]
wow

**Comment by Lucario2** [comment]
Make it that it hides players without items

**Comment by Lucario2** [comment]
Okay?

**Comment by PocketKiller** [comment]
you mean

**Comment by PocketKiller** [comment]
hides players that are nit creative or that their inventory is empty?

**Comment by Lucario2** [comment]
.

**Comment by Lucario2** [comment]
Hides all players all gamemodes always

**Comment by Lucario2** [comment]
okay?

**Comment by Lucario2** [comment]
and talk on collabedit.

**Comment by Lucario2** [comment]
...

**Comment by PocketKiller** [comment]
so everyone is never able to see each other? ok

**Comment by Lucario2** [comment]
Yes exactly.
